// <auto-generated />
using System;
using Deposit.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Deposit.API.Migrations
{
    [DbContext(typeof(DepositContext))]
    partial class DepositContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Deposit.API.Domain.Charge", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnName("id")
                        .HasColumnType("VARCHAR(38)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("DATETIME");

                    b.Property<int>("ProviderChargeId")
                        .HasColumnName("id_provider_charge")
                        .HasColumnType("INT");

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("INT");

                    b.Property<decimal>("Value")
                        .HasColumnName("value")
                        .HasColumnType("DECIMAL(19,2)");

                    b.HasKey("Id");

                    b.ToTable("CHARGE");
                });

            modelBuilder.Entity("Deposit.API.Domain.Deposit", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnName("id")
                        .HasColumnType("VARCHAR(38)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnName("id_account")
                        .HasColumnType("VARCHAR(38)");

                    b.Property<string>("ChargeId")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnName("id_charge")
                        .HasColumnType("VARCHAR(38)");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId");

                    b.ToTable("DEPOSIT");
                });

            modelBuilder.Entity("Deposit.API.Domain.Deposit", b =>
                {
                    b.HasOne("Deposit.API.Domain.Charge", "Charge")
                        .WithMany()
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
